<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Agents.Builder.Dialogs" Version="1.5.181" />
    <PackageReference Include="Microsoft.Agents.Hosting.AspNetCore" Version="1.5.181" />
  </ItemGroup>

</Project>
